### ISSUE TITLE
please make declarations independent from generator

### ISSUE THREAD

**Issue by runkelstein** [cypressious/kotlin-webextensions-declarations#23]
Hi,

thank you for making you work available.

I only want to get the declarations, and for now I think I don't need the entire generator. Is it possible to package it a little bit differently so that the declarations do not have a dependency on the generator and are thus more independent?

So than I could avoid adding additional repositories to my gradle file.
I Could build it just fine without additional repositories, but idea intelijii was marking everything red, because the generator module had certain dependencies which I would not get.

Thanks

**Comment by cypressious** [comment]
Hi @runkelstein,

When you're depending on `com.github.cypressious.kotlin-webextensions-declarations:webextensions-declarations`, you're only getting the declarations. They don't have any dependencies on the generator.

**Comment by runkelstein** [comment]
Hi  cypressious,

ok than maybee it is a problem with my gradle file or intelijii. I can build it without the generator, but intelijii marks it still red:

![image](https://user-images.githubusercontent.com/37014620/50007105-16675d80-ffb0-11e8-99a8-f6aea37b3f82.png)

That is my build.gradle.kt file:

```kotlin
import org.jetbrains.kotlin.gradle.tasks.Kotlin2JsCompile

plugins {
    id("kotlin2js") version Versions.kotlin apply true
}

repositories {
    jcenter()
    mavenCentral()
    maven("https://www.jitpack.io")
}

dependencies {
    compile(kotlin("stdlib-js", Versions.kotlin) )
}

allprojects  {

    apply {
        plugin("kotlin-dce-js")
        plugin("kotlin2js")
    }

    repositories {
        jcenter()
        mavenCentral()
        maven("https://www.jitpack.io")
    }

    dependencies {
        compile(kotlin("stdlib-js", Versions.kotlin))
        compile("com.github.cypressious", "kotlin-webextensions-declarations", Versions.kotlinWebextensions);
    }


    tasks {
        compileKotlin2Js {
            kotlinOptions {
                sourceMap = true
                kotlinOptions.sourceMapEmbedSources = "always"
            }
        }
    }


}
```

**Comment by runkelstein** [comment]
Ok, now I see it, I have to change that line
compile("com.github.cypressious", "kotlin-webextensions-declarations", Versions.kotlinWebextensions);
to
compile("com.github.cypressious.kotlin-webextensions-declarations", "webextensions-declarations", Versions.kotlinWebextensions);

then it is working as expected. Thanks for your reply.

**Comment by cypressious** [comment]
Perfect, thx for reporting your solution.
