### ISSUE TITLE
Problem with StorageNameSpace

### ISSUE THREAD

**Issue by runkelstein** [cypressious/kotlin-webextensions-declarations#24]
Hi, 

I just want to report that the StorageAPI is partly missing from the provided declarations in v0.3

Somehow this type
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea
is missing and some properties for the StorageNamespace as well.

The schema-File however contains definitions
https://github.com/mozilla/gecko-dev/blob/aaac9a77dd456360551dd764ffba4ca4899dcb56/toolkit/components/extensions/schemas/storage.json

So I suppose this is a problem with the generator.

I get around this by casting to dynamic which makes the code a bit more verbose.
So it is nothing urgent.

Kind Regards
Martin

**Comment by cypressious** [comment]
@runkelstein thx for reporting. There were two issues, namespace properties weren't generated and types could not have methods. I fixed those in v0.4. Please try the new version.

**Comment by runkelstein** [comment]
@cypressious Cool 👍, thank you. I tried it, and it works great.
